// <auto-generated />
using System;
using System.Collections.Generic;
using Jobbliggaren.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Jobbliggaren.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704145053_AddCompanyRegister")]
    partial class AddCompanyRegister
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jobbliggaren.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("GhostedThresholdDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(21)
                        .HasColumnName("ghosted_threshold_days");

                    b.Property<Guid?>("JobAdId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_ad_id");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<DateTimeOffset>("LastStatusChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_change_at");

                    b.Property<Guid?>("ResumeVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("JobSeekerId", "Status")
                        .HasDatabaseName("ix_applications_job_seeker_id_status");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Applications.ApplicationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.HasKey("Id")
                        .HasName("pk_application_notes");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_application_notes_application_id");

                    b.ToTable("application_notes", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Applications.FollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset?>("OutcomeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outcome_at");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id")
                        .HasName("pk_follow_ups");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_follow_ups_application_id");

                    b.ToTable("follow_ups", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ImpersonatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("impersonated_by");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id", "OccurredAt")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.CompanyWatches.CompanyWatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("OrganizationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("organization_number");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_company_watches");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_company_watches_user_id");

                    b.HasIndex("UserId", "OrganizationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_company_watches_user_orgnr_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("company_watches", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.CompanyWatches.FollowedCompanyAdHit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyWatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_watch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("JobAdId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_ad_id");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("notification_status");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_followed_company_ad_hits");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_followed_company_ad_hits_user_id");

                    b.HasIndex("UserId", "NotificationStatus")
                        .HasDatabaseName("ix_followed_company_ad_hits_user_status");

                    b.HasIndex("UserId", "JobAdId", "CompanyWatchId")
                        .IsUnique()
                        .HasDatabaseName("ux_followed_company_ad_hits_user_jobad_watch");

                    b.ToTable("followed_company_ad_hits", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.JobAds.JobAd", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentTypeConceptId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("employment_type_concept_id")
                        .HasComputedColumnSql("raw_payload->'employment_type'->>'concept_id'", true);

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExtractedLexemes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("jsonb")
                        .HasColumnName("extracted_lexemes")
                        .HasComputedColumnSql("jsonb_path_query_array(extracted_terms, '$[*].Lexeme')", true);

                    b.Property<string>("ExtractedTerms")
                        .HasColumnType("jsonb")
                        .HasColumnName("extracted_terms");

                    b.Property<string>("MunicipalityConceptId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("municipality_concept_id")
                        .HasComputedColumnSql("raw_payload->'workplace_address'->>'municipality_concept_id'", true);

                    b.Property<string>("OccupationGroupConceptId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("occupation_group_concept_id")
                        .HasComputedColumnSql("raw_payload->'occupation_group'->>'concept_id'", true);

                    b.Property<string>("OrganizationNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("organization_number")
                        .HasComputedColumnSql("raw_payload->'employer'->>'organization_number'", true);

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("RegionConceptId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("region_concept_id")
                        .HasComputedColumnSql("raw_payload->'workplace_address'->>'region_concept_id'", true);

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('swedish', coalesce(title,'') || ' ' || coalesce(description,''))", true);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("SsykConceptId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("ssyk_concept_id")
                        .HasComputedColumnSql("raw_payload->'occupation'->>'concept_id'", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.Property<string>("WorktimeExtentConceptId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("worktime_extent_concept_id")
                        .HasComputedColumnSql("raw_payload->'working_hours_type'->>'concept_id'", true);

                    b.HasKey("Id")
                        .HasName("pk_job_ads");

                    b.ToTable("job_ads", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.JobSeekers.JobSeeker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastCompanyWatchScanAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_company_watch_scan_at");

                    b.Property<DateTimeOffset?>("LastMatchScanAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_match_scan_at");

                    b.Property<DateTimeOffset?>("LastSeenJobsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_jobs_at");

                    b.Property<DateTimeOffset?>("LastSeenMatchesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_matches_at");

                    b.Property<string>("MatchPreferences")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("match_preferences")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("PrimaryResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_resume_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_job_seekers");

                    b.HasIndex("PrimaryResumeId")
                        .HasDatabaseName("ix_job_seekers_primary_resume_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_seekers_user_id");

                    b.ToTable("job_seekers", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Matching.UserJobAdMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<Guid>("JobAdId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_ad_id");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("notification_status");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("_matchedSkillConceptIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("matched_skill_concept_ids")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id")
                        .HasName("pk_user_job_ad_matches");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_job_ad_matches_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_user_job_ad_matches_user_created_at");

                    b.HasIndex("UserId", "JobAdId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_job_ad_matches_user_jobad");

                    b.HasIndex("UserId", "NotificationStatus")
                        .HasDatabaseName("ix_user_job_ad_matches_user_status");

                    b.ToTable("user_job_ad_matches", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.RecentJobSearches.RecentJobSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FilterHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("filter_hash");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<int>("LastSeenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_seen_count");

                    b.Property<DateTimeOffset>("LastViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_viewed_at");

                    b.Property<string>("Q")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("q");

                    b.Property<int>("SortBy")
                        .HasColumnType("integer")
                        .HasColumnName("sort_by");

                    b.PrimitiveCollection<List<string>>("_employer")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("employer_list");

                    b.PrimitiveCollection<List<string>>("_employmentType")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("employment_type_list");

                    b.PrimitiveCollection<List<string>>("_municipality")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("municipality_list");

                    b.PrimitiveCollection<List<string>>("_occupationGroup")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("occupation_group_list");

                    b.PrimitiveCollection<List<string>>("_region")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("region_list");

                    b.PrimitiveCollection<List<string>>("_worktimeExtent")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("worktime_extent_list");

                    b.HasKey("Id")
                        .HasName("pk_recent_job_searches");

                    b.HasIndex("JobSeekerId", "FilterHash")
                        .IsUnique()
                        .HasDatabaseName("ux_recent_job_searches_seeker_hash");

                    b.HasIndex("JobSeekerId", "LastViewedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_recent_job_searches_seeker_viewed_at");

                    b.ToTable("recent_job_searches", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Resumes.Parsing.ParsedResume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parse_confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DetectedLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("detected_language");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<string>("ParsedContentEnc")
                        .HasColumnType("text")
                        .HasColumnName("parsed_content_enc");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("personnummer_scan");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SourceContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_content_type");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("source_file_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("_occupationProposals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("occupation_proposals");

                    b.Property<string>("_skillProposals")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("skill_proposals")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_parsed_resumes");

                    b.HasIndex("JobSeekerId")
                        .HasDatabaseName("ix_parsed_resumes_job_seeker_id");

                    b.ToTable("parsed_resumes", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Resumes.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("LatestRole")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("latest_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("section_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<string>>("_topSkills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("top_skills");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.HasIndex("JobSeekerId")
                        .HasDatabaseName("ix_resumes_job_seeker_id");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Resumes.ResumeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentEnc")
                        .HasColumnType("text")
                        .HasColumnName("content_enc");

                    b.Property<string>("ContentLegacyJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_resume_versions");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_resume_versions_resume_id");

                    b.ToTable("resume_versions", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.SavedJobAds.SavedJobAd", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobAdId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_ad_id");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_job_ads");

                    b.HasIndex("JobSeekerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_saved_job_ads_seeker_created_at");

                    b.HasIndex("JobSeekerId", "JobAdId")
                        .IsUnique()
                        .HasDatabaseName("ux_saved_job_ads_seeker_jobad");

                    b.ToTable("saved_job_ads", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Domain.SavedSearches.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("NotificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notification_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_saved_searches");

                    b.HasIndex("JobSeekerId")
                        .HasDatabaseName("ix_saved_searches_job_seeker_id");

                    b.ToTable("saved_searches", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Infrastructure.CompanyRegister.ScbCompanyRegisterEntry", b =>
                {
                    b.Property<string>("OrganizationNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("organization_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasAdvertisingBlock")
                        .HasColumnType("boolean")
                        .HasColumnName("reklamsparr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ScbStatusRaw")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("scb_status_raw");

                    b.Property<string>("SeatMunicipalityCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("sate_kommun_code");

                    b.Property<string>("SeatMunicipalityName")
                        .HasColumnType("text")
                        .HasColumnName("sate_kommun_name");

                    b.PrimitiveCollection<List<string>>("SniCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sni_codes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("OrganizationNumber")
                        .HasName("pk_company_register");

                    b.HasIndex("SeatMunicipalityCode")
                        .HasDatabaseName("ix_company_register_sate_kommun_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_company_register_status");

                    b.HasIndex("SyncedAt")
                        .HasDatabaseName("ix_company_register_synced_at");

                    b.ToTable("company_register", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Infrastructure.JobAds.SnapshotMisses.JobAdSnapshotMiss", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("FirstMissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_missed_at");

                    b.Property<DateTimeOffset?>("LastMissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_missed_at");

                    b.Property<int>("MissCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("miss_count");

                    b.HasKey("Source", "ExternalId")
                        .HasName("pk_job_ad_snapshot_misses");

                    b.HasIndex("Source", "MissCount")
                        .HasDatabaseName("ix_job_ad_snapshot_misses_miss_count")
                        .HasFilter("\"miss_count\" >= 1");

                    b.ToTable("job_ad_snapshot_misses", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Infrastructure.Persistence.UserDataKey", b =>
                {
                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<int>("DekVersion")
                        .HasColumnType("integer")
                        .HasColumnName("dek_version");

                    b.Property<string>("CmkKeyId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cmk_key_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_dek");

                    b.HasKey("JobSeekerId", "DekVersion")
                        .HasName("pk_user_data_keys");

                    b.ToTable("user_data_keys", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Infrastructure.Taxonomy.TaxonomyConcept", b =>
                {
                    b.Property<string>("ConceptId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("concept_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<string>("ParentConceptId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("parent_concept_id");

                    b.HasKey("ConceptId")
                        .HasName("pk_taxonomy_concepts");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_taxonomy_concepts_kind");

                    b.HasIndex("ParentConceptId")
                        .HasDatabaseName("ix_taxonomy_concepts_parent_concept_id");

                    b.ToTable("taxonomy_concepts", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Infrastructure.Taxonomy.TaxonomyRelation", b =>
                {
                    b.Property<string>("SourceConceptId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_concept_id");

                    b.Property<string>("RelatedConceptId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("related_concept_id");

                    b.Property<string>("Kind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.HasKey("SourceConceptId", "RelatedConceptId", "Kind")
                        .HasName("pk_taxonomy_relations");

                    b.ToTable("taxonomy_relations", (string)null);
                });

            modelBuilder.Entity("Jobbliggaren.Infrastructure.Taxonomy.TaxonomySnapshotMeta", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("SeededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seeded_at");

                    b.Property<string>("TaxonomyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("taxonomy_version");

                    b.HasKey("Id")
                        .HasName("pk_taxonomy_snapshot_meta");

                    b.ToTable("taxonomy_snapshot_meta", null, t =>
                        {
                            t.HasCheckConstraint("ck_taxonomy_snapshot_meta_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Applications.Application", b =>
                {
                    b.OwnsOne("Jobbliggaren.Domain.Applications.AdSnapshot", "AdSnapshot", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("snapshot_captured_at");

                            b1.Property<string>("Company")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("snapshot_company");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("snapshot_description");

                            b1.Property<DateTimeOffset?>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("snapshot_expires_at");

                            b1.Property<string>("MunicipalityConceptId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("snapshot_municipality_concept_id");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("snapshot_published_at");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("snapshot_source");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("snapshot_title");

                            b1.Property<string>("Url")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("snapshot_url");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId")
                                .HasConstraintName("fk_applications_applications_id");
                        });

                    b.OwnsOne("Jobbliggaren.Domain.Applications.ManualPosting", "ManualPosting", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Company")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("manual_company");

                            b1.Property<DateTimeOffset?>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("manual_expires_at");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("manual_title");

                            b1.Property<string>("Url")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("manual_url");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId")
                                .HasConstraintName("fk_applications_applications_id");
                        });

                    b.Navigation("AdSnapshot");

                    b.Navigation("ManualPosting");
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Applications.ApplicationNote", b =>
                {
                    b.HasOne("Jobbliggaren.Domain.Applications.Application", null)
                        .WithMany("Notes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_notes_applications_application_id");
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Applications.FollowUp", b =>
                {
                    b.HasOne("Jobbliggaren.Domain.Applications.Application", null)
                        .WithMany("FollowUps")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follow_ups_applications_application_id");
                });

            modelBuilder.Entity("Jobbliggaren.Domain.JobAds.JobAd", b =>
                {
                    b.OwnsOne("Jobbliggaren.Domain.JobAds.Company", "Company", b1 =>
                        {
                            b1.Property<Guid>("JobAdId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("company_name");

                            b1.HasKey("JobAdId");

                            b1.ToTable("job_ads");

                            b1.WithOwner()
                                .HasForeignKey("JobAdId")
                                .HasConstraintName("fk_job_ads_job_ads_id");
                        });

                    b.OwnsOne("Jobbliggaren.Domain.JobAds.ExternalReference", "External", b1 =>
                        {
                            b1.Property<Guid>("JobAdId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("external_id");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("external_source");

                            b1.HasKey("JobAdId");

                            b1.HasIndex("Source", "ExternalId")
                                .IsUnique()
                                .HasDatabaseName("ix_job_ads_external_source_external_id")
                                .HasFilter("\"external_id\" IS NOT NULL");

                            b1.ToTable("job_ads");

                            b1.WithOwner()
                                .HasForeignKey("JobAdId")
                                .HasConstraintName("fk_job_ads_job_ads_id");
                        });

                    b.Navigation("Company")
                        .IsRequired();

                    b.Navigation("External");
                });

            modelBuilder.Entity("Jobbliggaren.Domain.JobSeekers.JobSeeker", b =>
                {
                    b.OwnsOne("Jobbliggaren.Domain.JobSeekers.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("JobSeekerId");

                            b1.Property<bool>("BackgroundMatchNotificationsEnabled");

                            b1.Property<int>("DigestCadence");

                            b1.Property<DateTimeOffset?>("FollowedCompanyNotificationConsentAt");

                            b1.Property<DateTimeOffset?>("FollowedCompanyNotificationConsentWithdrawnAt");

                            b1.Property<bool>("FollowedCompanyNotificationsEnabled");

                            b1.Property<string>("Language")
                                .IsRequired();

                            b1.Property<DateTimeOffset?>("NotificationConsentAt");

                            b1.Property<DateTimeOffset?>("NotificationConsentWithdrawnAt");

                            b1.HasKey("JobSeekerId");

                            b1.ToTable("job_seekers");

                            b1
                                .ToJson("preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("JobSeekerId")
                                .HasConstraintName("fk_job_seekers_job_seekers_id");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Resumes.ResumeVersion", b =>
                {
                    b.HasOne("Jobbliggaren.Domain.Resumes.Resume", null)
                        .WithMany("Versions")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_versions_resumes_resume_id");
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Applications.Application", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Jobbliggaren.Domain.Resumes.Resume", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
