using System.Globalization;
using System.Text;
using Jobbliggaren.QA.Corpus.Harness;
using Jobbliggaren.QA.Corpus.Layout;

namespace Jobbliggaren.QA.Corpus.Reporting;

/// <summary>
/// Everything the layout report renders.
///
/// <para><b>The frequency prohibition is enforced STRUCTURALLY, not by a word blacklist.</b> This
/// record has no field that aggregates an OBSERVED value across cases: the only cross-case
/// collections are instrument-health case-id lists. A percentage, a share, or an "n of 16" is
/// therefore unrepresentable without widening this record, which is visible in review. A token
/// blacklist was considered and rejected — it fails on the report's own mandated header text, and
/// a name-based guard where a shape-based one is available is a defect class this repo has already
/// paid for.</para>
/// </summary>
public sealed record LayoutCorpusReportData(
    string BaseCommit,
    IReadOnlyList<LayoutCaseObservation> Cases,
    IReadOnlyList<string> SubstitutedPorts,
    IReadOnlyList<string> ModelSymmetryProblems);

/// <summary>
/// Builds the layout corpus artifact. Pure string assembly — deterministic, no clock, and it never
/// echoes a personnummer (the pnr-bearing case reports presence as a boolean; the value is never
/// printed to the artifact, a log, or the committed baseline).
///
/// <para><b>Observe-only.</b> Nothing in the tables below is asserted. A value moving is a finding
/// to read against the committed baseline, never a build failure. Ratcheting any of it to a floor
/// requires an explicit Klas decision (CLAUDE.md §2.5), and any future ratchet must be stated as a
/// POSITIVE verdict over named case ids — never as a negation, because "no case is silently lossy"
/// is satisfied by a run in which everything blocks.</para>
/// </summary>
public static class LayoutCorpusReport
{
    /// <summary>The claim-discipline paragraph, verbatim and pinned by an emitter test. ADR 0109
    /// §4 forbids deriving a population frequency from synthetic data; this corpus answers a
    /// different question — per-class survival — and the header must say which.</summary>
    public const string ClaimDiscipline =
        "Every row below is a PER-CASE BOOLEAN over ONE authored synthetic document. N = 1 per "
        + "case. This corpus contains no sample of real CVs and licenses no frequency claim: not a "
        + "percentage, not \"most\", not \"commonly\", not \"typically\". The only sentence form "
        + "this data supports is: \"the authored document <case> exhibits <property>\". Every count "
        + "in this file is a count of authored fixtures or of items inside a single fixture; none "
        + "is a count of anything in the world.";

    /// <summary>The observe-only paragraph, verbatim and pinned by an emitter test.</summary>
    public const string ObserveOnly =
        "OBSERVE-ONLY: nothing in the tables below is asserted. A value that moves is a finding to "
        + "read against the committed baseline, not a build failure. Ratcheting requires an "
        + "explicit Klas ratchet (CLAUDE.md §2.5), and any ratchet must be stated as a positive "
        + "verdict over named case ids, never as a negation.";

    /// <summary>The vendor-naming paragraph, verbatim and pinned by an emitter test.</summary>
    public const string VendorDiscipline =
        "VENDOR DISCIPLINE: every case is named for its MECHANIC. No genuine Canva, Word, "
        + "InDesign, LaTeX or Europass export was run through the extractor for this report. "
        + "\"docx\" names a container format, not a producer.";

    public static string Build(LayoutCorpusReportData d)
    {
        ArgumentNullException.ThrowIfNull(d);
        var sb = new StringBuilder();
        void L(string s = "") => sb.AppendLine(s);
        void LI(FormattableString s) => sb.AppendLine(s.ToString(CultureInfo.InvariantCulture));

        L("# Jobbliggaren — CV layout corpus, from bytes (#1060 PR K)");
        L();
        L("> Machine-generated by `LayoutCorpusReportTests`. The EMITTER is the deliverable; this");
        L("> artifact is regenerated on demand. Regenerate with:");
        L(">");
        L("> ```");
        L("> dotnet build tests/Jobbliggaren.QA.Corpus/Jobbliggaren.QA.Corpus.csproj");
        L("> cd tests/Jobbliggaren.QA.Corpus/bin/Debug/net10.0");
        L("> ./Jobbliggaren.QA.Corpus.exe -class \"Jobbliggaren.QA.Corpus.LayoutCorpusReportTests\"");
        L("> ```");
        L(">");
        LI($"> Base commit: `{d.BaseCommit}`.");
        L("> Deterministic; NO AI/LLM anywhere in the measured chain (ADR 0071).");
        L();
        L("## Claim discipline (ADR 0109 §4)");
        L();
        L("> " + ClaimDiscipline);
        L();
        L("> " + VendorDiscipline);
        L();
        L("> " + ObserveOnly);
        L();
        L("## Divergence disclosure");
        L();
        L("What this run is NOT, stated up front rather than left for a reader to discover:");
        L();
        L("- EF InMemory: no database server, no container, no network, not the shared dev DB. It");
        L("  IS an EF provider with real change tracking and real global query filters — never");
        L("  read this as \"no persistence layer\".");
        L("- No DEK envelope round-trip, no SQL translation, no SmartEnum translation. Those stay");
        L("  proven by `AutoPromoteParsedResumeEncryptionTests` and the integration suites.");
        L("- No Mediator pipeline: no logging, validation, authorization or UnitOfWork behavior.");
        // REWRITTEN 2026-08-01 by the PR that made the previous sentence false, exactly as that
        // sentence's own note required. It read: "The `IncompleteContent` SUB-reason is
        // unavailable: `AutoPromoteGate.Evaluate` discards `created.Error`…". The gate no longer
        // discards it (#1060 D3(β) PR 2), and this harness no longer passes NullLogger.
        L("- The `IncompleteContent` sub-reason IS readable, and §5's `Domain code` column is where");
        L("  it is published. `AutoPromoteGate` carries `created.Error.Code` verbatim on that arm");
        L("  and the handler emits it as the `BlockDetail` property; this harness reads that");
        L("  property off the real log line, because `AutoPromoteGateVerdict` is `internal` to");
        L("  `Jobbliggaren.Application` and this assembly is not in its `InternalsVisibleTo` list.");
        L("  Nothing is re-typed: the code is the FIRST evaluation's output, not a second opinion.");
        L("- Substituted ports (none of them feeds an auto-promote gate):");
        foreach (var p in d.SubstitutedPorts)
            L($"  - {p}");
        L();

        // ── Section 0 — instrument integrity, as case-id LISTS. Never a ratio: an "n/16" is
        // itself the shape ADR 0109 §4 warns about.
        L("## 0. Instrument integrity");
        L();
        L(IdLine("byte proofs held", d.Cases.Where(c => c.ByteProofFailure is null)));
        L(IdLine("byte proofs FAILED", d.Cases.Where(c => c.ByteProofFailure is not null)));
        L(IdLine("crashed", d.Cases.Where(c => c.CrashedWithExceptionType is not null)));
        L(IdLine("fixture invalid", d.Cases.Where(c => c.FixtureProblems.Count > 0)));
        L(IdLine("gate ladder malformed", d.Cases.Where(c => !GateLadder.IsWellFormed(c.Gates))));
        // An INSTRUMENT line, beside the other four, and not a product statement: the handler
        // emitted a LeftPending whose `BlockDetail` property this harness could not read (renamed,
        // removed, or ambiguous). Listed separately from "no domain code" for the reason
        // GateState.Unresolved exists — an em-dash that could mean either would let a reading
        // failure publish as a fact about the CV.
        L(IdLine("block detail unreadable", d.Cases.Where(c => c.BlockDetailUnreadable)));
        if (d.ModelSymmetryProblems.Count > 0)
        {
            L();
            L("**Model symmetry problems (pin P5 cannot hold):**");
            foreach (var p in d.ModelSymmetryProblems)
                L($"- {p}");
        }

        foreach (var c in d.Cases.Where(c => c.ByteProofFailure is not null))
            L($"- `{c.Case.Id}`: {c.ByteProofFailure}");
        L();

        // ── Section 1 — the fidelity ledger.
        L("## 1. Fidelity ledger");
        L();
        L("Provenance is per SECTION, not per case. The 2026-07-26 spike measured extraction and");
        L("segmentation only — it produced no gate verdict, no promote boolean and no delta on a");
        L("promoted CV. So the \"promote measured?\" column reads `no` for every row until this");
        L("suite runs. There is deliberately no per-row promote-provenance column: it would be the");
        L("literal \"no\" on every row forever, which is a decoration rather than a measurement.");
        L();
        L("| # | Case id | CTO class | Container | One-variable step from | Extract+segment spike-measured? | Byte proof |");
        L("|---|---|---|---|---|---|---|");
        for (var i = 0; i < d.Cases.Count; i++)
        {
            var c = d.Cases[i].Case;
            LI($"| {i + 1} | `{c.Id}` | {c.CtoClass} | {c.Container} | {c.OneVariableStepFrom ?? "—"} | {(c.SpikeMeasuredExtractSegment ? "yes" : "no")} | {c.ByteProofDescription} |");
        }

        L();
        L("**Mechanics**");
        L();
        foreach (var c in d.Cases)
            L($"- `{c.Case.Id}` — {c.Case.Mechanic}");
        L();

        // ── Section 2 — the headline.
        L("## 2. Fidelity verdict");
        L();
        L("`With period` counts PROMOTED experiences carrying a non-blank `RawPeriod`, and nothing");
        L("else. It was once called `Well-formed` and also tested Role and Company — both REQUIRED by");
        L("`Resume.ValidateContent`, so on a promoted row they are true by invariant and the count was");
        L("period-presence wearing a validity name. It has equalled `Promoted exp` in every baseline");
        L("published so far: no fixture yet distinguishes them, which is a fact about the fixtures.");
        L();
        L("| # | Case | Verdict | GT emp | Parsed exp | Promoted exp | With period | GT edu | Parsed edu | Promoted edu | First blocking gate |");
        L("|---|---|---|---|---|---|---|---|---|---|---|");
        for (var i = 0; i < d.Cases.Count; i++)
        {
            var c = d.Cases[i];
            LI($"| {i + 1} | `{c.Case.Id}` | **{c.Verdict}** | {c.GroundTruthExperience} | {N(c.ParsedExperience)} | {N(c.PromotedExperience)} | {N(c.PromotedExperienceWithRawPeriod)} | {c.GroundTruthEducation} | {N(c.ParsedEducation)} | {N(c.PromotedEducation)} | {c.BlockReason?.ToString() ?? "—"} |");
        }

        L();

        // ── Section 3 — the money table.
        L("## 3. Marker trace");
        L();
        L("One row per authored employment and education. A count says five became one; this says");
        L("WHICH four vanished and where each was last seen. `RetainedButOrphaned` on a promoted");
        L("row is the finding: the product said the CV was saved and this employment is gone.");
        L();
        L("| Case | Kind | Marker | In bytes | In parsed artifact | In promoted section | Found in other section | Verdict |");
        L("|---|---|---|---|---|---|---|---|");
        foreach (var c in d.Cases)
        {
            foreach (var m in c.Markers)
            {
                LI($"| `{c.Case.Id}` | {m.Kind} | {m.Marker} | {Y(m.InExtractedBytes)} | {Y(m.InParsedArtifact)} | {Y(m.InPromotedSectionSpan)} | {m.FoundInOtherSection ?? "—"} | **{m.Verdict}** |");
            }
        }

        L();

        // ── Section 4 — extraction and form.
        L("## 4. Extraction and form");
        L();
        L("| # | Case | Kind resolved | Status | Chars | Lines | BLANK LINES | Segment ran | Language | Headings | Preamble |");
        L("|---|---|---|---|---|---|---|---|---|---|---|");
        for (var i = 0; i < d.Cases.Count; i++)
        {
            var c = d.Cases[i];
            LI($"| {i + 1} | `{c.Case.Id}` | {Y(c.KindResolved)} | {c.ExtractionStatus?.ToString() ?? "—"} | {c.CharCount} | {c.LineCount} | **{c.BlankLineCount}** | {Y(c.SegmentRan)} | {c.DetectedLanguage ?? "—"} | {c.HeadingsDetected} | {(c.PreambleChars is null ? "null" : $"{c.PreambleChars} chars")} |");
        }

        L();
        L("### 4b. Product-side observables");
        L();
        L("Each row above pairs a byte proof (what the AUTHORED document is) with what the product");
        L("actually emitted. A byte proof alone restates the generator; an observable alone does not");
        L("say which shape produced it. The digest is a per-case value — two rows sharing one is a");
        L("reader's inference, never an emitted ratio.");
        L();
        L("| # | Case | Text digest | Fused period+role line | A line carries both columns | First extracted line |");
        L("|---|---|---|---|---|---|");
        for (var i = 0; i < d.Cases.Count; i++)
        {
            var c = d.Cases[i];
            LI($"| {i + 1} | `{c.Case.Id}` | `{c.ExtractedTextDigest}` | {Y(c.ContainsFusedPeriodRole)} | {Y(c.AnyLineCarriesBothColumns)} | {Quote(c.FirstExtractedLine)} |");
        }

        L();
        L("**Twin comparisons** — the only honest sentence this corpus can emit about tables. The");
        L("DOCX extractor handles `w:t` and `w:p` only, with no `w:tbl`/`w:tr`/`w:tc` handling, so a");
        L("table and a flat paragraph sequence in the same order should produce identical text. An");
        L("ordering assertion would restate our own writer; equal digests are a fact about the");
        L("extractor.");
        L();
        foreach (var c in d.Cases.Where(x => x.Case.OneVariableStepFrom is not null))
        {
            var twin = d.Cases.FirstOrDefault(x => x.Case.Id == c.Case.OneVariableStepFrom);
            if (twin is null)
                continue;

            var same = string.Equals(
                c.ExtractedTextDigest, twin.ExtractedTextDigest, StringComparison.Ordinal);
            LI($"- `{c.Case.Id}` vs `{c.Case.OneVariableStepFrom}` — digests {(same ? "**EQUAL**" : "differ")} (`{c.ExtractedTextDigest}` / `{twin.ExtractedTextDigest}`)");
        }

        L();

        // ── Section 5 — the gate ladder.
        L("## 5. Gate ladder");
        L();
        L("No predicate expression is re-typed anywhere in this corpus; the states are derived from");
        L("what the real handler returned. **TWO** predicates still collapse onto one");
        L("`PersonnummerPresent` token, and each is settled by its own POSITIVE discriminator — the");
        L("aggregate's own flag for the parse rung, the two PUBLIC calls the handler makes for the");
        L("label rung. The DQ6 guard is no longer among them: #1060 PR C gave it its own");
        L("`PersonnummerInAccountName` token, so that rung is reached by name.");
        L();
        L("Earlier revisions said these were resolved \"by ELIMINATION — whatever remains IS the DQ6");
        L("guard, there is no fourth site\". That reasoning was sound only while the site list was");
        L("known complete, and PR C is the measured proof that such knowledge expires. Nothing is");
        L("inferred from a remainder now; what falls past both guards is reported as `unresolved`.");
        L();
        // DELIBERATELY UNPINNED, unlike the three disclaimers. Those are protections a well-meaning
        // edit can SOFTEN, so they are asserted verbatim. This is a DEFINITION: delete it and no
        // false claim appears, only an undefined word a reader notices immediately. A shape-based
        // guard is not available either — "every word the renderer emits is glossed here" is false
        // today by design, since `passed` and `**BLOCKED**` need no gloss. Same treatment
        // Report_NeverRendersAPercentage already gives the token blacklist it rejected.
        L("A gate cell renders one of six words. `passed` and `**BLOCKED**` say what they say; the");
        L("FOUR below are the confusable ones, and conflating two of them is what this section was");
        L("corrected for (2026-07-28):");
        L();
        L("- `not evaluated` — an earlier GATE stopped control, so this rung was never asked.");
        L("- `no verdict` — the handler returned a genuine FAULT, so no gate decided anything.");
        L("- `unresolved` — THE INSTRUMENT has no arm for the token the handler returned. It is an");
        L("  integrity failure, listed in §0 and red in the suite, never a statement about the");
        L("  product. Before it existed, this case rendered as `no verdict` — publishing an honest");
        L("  block as a handler fault, on the one case that exercises the DQ6 rung.");
        L("- `—` — no ladder exists at all: the case CRASHED before any gate was reached, so there is");
        L("  nothing for the rungs to report. §0 names it. Distinct from `no verdict`, which is a");
        L("  statement about the handler; here the handler was never asked.");
        L();
        L("`Domain code` is the constraint `Resume.CreateFromParsed` refused on, carried verbatim");
        L("out of the buildability rung and read off the handler's own `BlockDetail` log property");
        L("(#1060 D3(β) PR 2). It is what makes `**BLOCKED**` on that rung legible: the token");
        L("`IncompleteContent` covers every code `Resume.CreateFromParsed` can return: thirty-two");
        L("declared by `Resume.ValidateContent`, plus `JobSeekerIdRequired` and `ValidateName`'s");
        L("three, so thirty-six. They do not share a fix — a per-entry failure like");
        L("`Resume.ExperienceCompanyRequired` is routable, while a whole-document one like");
        L("`Resume.SummaryTooLong` is not, and a design that assumed the first would spend a");
        L("Domain refactor against a failure it cannot touch.");
        L();
        L("Read `—` in that column as **\"no Domain refusal produced a code on this row\"**, never");
        L("as \"no constraint failed\": a personnummer block and a promote both print it, and");
        L("neither asked the Domain the question. A row whose code could not be READ prints");
        L("`INSTRUMENT: unreadable` instead and is named in §0 — the two are never one em-dash.");
        L();
        // From the LADDER, not from Cases[0]. A crashed first case carries an empty ladder by
        // construction, and reading the headings off it produced a six-cell header over a five-cell
        // delimiter — under GFM, no table at all. The section disappeared entirely.
        var gateHeaders = GateLadder.RungHeaders;
        // `Domain code` sits beside FIRST BLOCK, where the buildability rung lives, and in §5
        // ONLY (CTO-bind D.3): §2 is the headline verdict table and already carries eleven
        // columns, so a twelfth diagnostic one would make the headline unreadable AND give the
        // detail two homes in one document.
        L($"| # | Case | {string.Join(" | ", gateHeaders)} | FIRST BLOCK | Domain code | Promote fault | Promoted |");
        // DERIVED, never a literal. The rung count changed with #1060's gate retirement, and the
        // hardcoded delimiter this replaces was already one cell short of its own header — under
        // GFM a delimiter row that does not match the header cell count means the block is not
        // recognised as a table at all, so §5 rendered as raw pipes on GitHub. Deriving it makes
        // the next rung change unable to reintroduce that.
        // +6, not +5, since `Domain code` landed: #, Case, FIRST BLOCK, Domain code, Promote
        // fault, Promoted. Derived from the count rather than written out, so the next column
        // cannot reintroduce the mismatch that made §5 render as raw pipes on GitHub.
        L($"|{string.Concat(Enumerable.Repeat("---|", gateHeaders.Count + 6))}");
        for (var i = 0; i < d.Cases.Count; i++)
        {
            var c = d.Cases[i];
            // A case with no ladder (a crash — nothing evaluated any gate) still occupies every
            // column, as em-dashes. Letting the row run short would leave GFM to pad it with blanks,
            // and a blank cell under "G3a pnr(DQ6)" reads as a verdict rather than as its absence.
            var cells = c.Gates.Count > 0
                ? string.Join(" | ", c.Gates.Select(g => Short(g.State)))
                : string.Join(" | ", Enumerable.Repeat("—", gateHeaders.Count));
            LI($"| {i + 1} | `{c.Case.Id}` | {cells} | {c.BlockReason?.ToString() ?? "—"} | {DomainCode(c)} | {c.PromoteFailureCode ?? "—"} | {Y(c.Promoted)} |");
        }

        L();
        L("**Observed Domain state** (this is aggregate state, NOT a gate verdict). The personnummer");
        L("column prints the AUTHORED declaration and the OBSERVED aggregate flag side by side: if");
        L("extraction ever loses an authored personnummer, that divergence is itself the finding, and");
        L("a column printing only the declaration would hide it behind the very content loss this");
        L("corpus measures. The value itself is never printed.");
        L();
        L("| Case | Confidence overall | Preamble on parse | Preamble ON THE PROMOTED CV | pnr authored (body / account) | pnr OBSERVED on parse |");
        L("|---|---|---|---|---|---|");
        foreach (var c in d.Cases)
        {
            LI($"| `{c.Case.Id}` | {c.ConfidenceOverall ?? "—"} | {Y(c.PreambleChars is not null)} | {(c.Promoted ? Y(c.PromotedPreambleChars is not null) : "—")} | {AuthoredPnr(c)} | {YN(c.PersonnummerFoundOnParse)} |");
        }

        L();

        // ── Section 6 — the segmenter's own words.
        L("## 6. Section confidence, verbatim");
        L();
        L("The segmenter's own evidence strings, quoted exactly and never paraphrased, with the");
        L("authored ground truth beside them. `Confident — heading matched, 1 entries` next to");
        L("`ground truth: 5 employments` IS the finding.");
        L();
        foreach (var c in d.Cases.Where(c => c.SectionEvidence.Count > 0))
        {
            LI($"**`{c.Case.Id}`** — ground truth: {c.GroundTruthExperience} employments, {c.GroundTruthEducation} educations");
            L();
            foreach (var e in c.SectionEvidence)
                L($"- `{e}`");
            L();
        }

        // ── Section 7 — contamination.
        L("## 7. Cross-section contamination");
        L();
        L("An authored string turning up in a section that is not its declared home. Measured as");
        L("membership of the corpus's own declarations, never by re-typing what counts as a language,");
        L("and only against the project heading the case ACTUALLY rendered. This SURVIVES the");
        L("blank-line fix — it is present in the correct-count control arm — so a reader must not");
        L("read a zero content-loss delta as \"clean\".");
        L();
        L("Precision limit, stated: an entry that is a proper fragment of an authored project line is");
        L("reported AS a fragment (the list parser atomises prose on commas). An entry that is neither");
        L("an authored line nor a fragment of one is invisible here — this sweep can under-report, and");
        L("it never over-reports.");
        L();
        var contaminated = d.Cases.Where(c => c.CrossSectionContamination.Count > 0).ToList();
        if (contaminated.Count == 0)
        {
            L("No case in this run reported contamination.");
        }
        else
        {
            L("| Case | Receiving section ← foreign string |");
            L("|---|---|");
            foreach (var c in contaminated)
            {
                foreach (var f in c.CrossSectionContamination)
                    L($"| `{c.Case.Id}` | {f} |");
            }
        }

        L();

        // ── Section 8 — the two pins that need their own shape.
        L("## 8. Pin P7 (unknown heading) and pin P5 (English non-difference)");
        L();
        L("P7 is a three-part predicate: the promoted Summary contains the unknown heading verbatim,");
        L("AND no parsed section is headed by it, AND the Summary stays under the 2000-char domain");
        L("cap (above it `Resume.ValidateContent` refuses on `SummaryTooLong` and the row would");
        L("silently measure `IncompleteContent` under P7's name). Position is load-bearing: measured");
        L("2026-07-26, the same heading after UTBILDNING is swallowed by Education and after SPRÅK");
        L("by the Languages list.");
        L();
        L("Each row is measured against the heading THAT case renders, not against a fixed constant:");
        L("the control renders the known synonym, so measuring it against the unknown one made both");
        L("its cells read \"no\" unconditionally — a control that cannot fall is not a control.");
        L();
        L("| Case | Heading rendered | In promoted Summary | Is its own parsed section | Parsed free sections | Summary chars |");
        L("|---|---|---|---|---|---|");
        foreach (var c in d.Cases.Where(c =>
            c.Case.Id.Contains("heading-after-profile", StringComparison.Ordinal)))
        {
            var sections = c.ParsedFreeSectionHeadings.Count == 0
                ? "none"
                : string.Join(", ", c.ParsedFreeSectionHeadings.Select(h => $"`{h}`"));
            LI($"| `{c.Case.Id}` | `{c.Case.ProjectHeadingRendered}` | {YN(c.SummaryContainsRenderedProjectHeading)} | {YN(c.RenderedProjectHeadingIsOwnSection)} | {sections} | {N(c.PromotedSummaryChars)} |");
        }

        L();
        L("P5 compares the STRUCTURAL tuple of the Swedish and English single-column cases. Text-");
        L("bearing fields are excluded by name: they differ by construction between a document and");
        L("its translation and would drown a real regression in permanent noise. The one field");
        L("permitted to differ is the detected language.");
        L();
        var sv = d.Cases.FirstOrDefault(c => c.Case.Id == "pdf-single-column-sv");
        var en = d.Cases.FirstOrDefault(c => c.Case.Id == "pdf-single-column-en");
        if (sv is not null && en is not null)
        {
            L("| Field | Swedish | English |");
            L("|---|---|---|");
            LI($"| detected language (permitted to differ) | {sv.DetectedLanguage ?? "—"} | {en.DetectedLanguage ?? "—"} |");
            LI($"| parsed experience | {N(sv.ParsedExperience)} | {N(en.ParsedExperience)} |");
            LI($"| parsed education | {N(sv.ParsedEducation)} | {N(en.ParsedEducation)} |");
            LI($"| headings detected | {sv.HeadingsDetected} | {en.HeadingsDetected} |");
            LI($"| first blocking gate | {sv.BlockReason?.ToString() ?? "—"} | {en.BlockReason?.ToString() ?? "—"} |");
            LI($"| promoted | {Y(sv.Promoted)} | {Y(en.Promoted)} |");
            LI($"| fidelity verdict | {sv.Verdict} | {en.Verdict} |");
        }

        L();

        // ── Section 9 — what this instrument cannot see.
        L("## 9. Known precision gaps and deliberate omissions");
        L();
        L("- **No genuine vendor export.** The CTO's class (d) is answered PARTIALLY: the mechanic");
        L("  is reproduced, the vendor claim is not made.");
        L("- **Table-ness is invisible to the DOCX extractor** (it handles `w:t` and `w:p` only —");
        L("  no `w:tbl`/`w:tr`/`w:tc`), so class (c) is answered as a container fact with its");
        L("  invisibility shipped as a measurement, not as a distinct extraction mechanic.");
        L("- **Scanned / `NoTextLayer` documents are absent**, so the `ParseConfidence.Failed`");
        L("  branch of the import handler's segment conditional is unexercised.");
        L("- **Kerning-driven word splits, ligature artefacts, rotated text and foreign-producer");
        L("  ToUnicode tables are absent.** Every PDF here round-trips through a QuestPDF-embedded");
        L("  subset font and its own CMap — a real mechanism, but QuestPDF's.");
        L("- **The `addDoubleNewline: true` counterfactual is NOT reproduced by this suite.** Doing");
        L("  it faithfully would mean hand-copying the extractor's whole page-assembly loop (the");
        L("  page cap, the char budget with its truncate-and-break arm, the seam, `Normalize`) —");
        L("  exactly the re-typed-production defect this corpus exists to avoid. The measurement");
        L("  lives in the committed baseline's appendix.");
        L("- **No case is asserted.** Every falsifier named in the PR body produces a silently");
        L("  different artifact and a green build. This file helps only a reader who diffs it");
        L("  against the committed baseline. That is what observe-only means.");
        L();

        return sb.ToString();
    }

    private static string IdLine(string label, IEnumerable<LayoutCaseObservation> cases)
    {
        var ids = cases.Select(c => $"`{c.Case.Id}`").ToList();
        return $"- **{label}:** {(ids.Count == 0 ? "none" : string.Join(", ", ids))}";
    }

    private static string N(int? v) => v?.ToString(CultureInfo.InvariantCulture) ?? "—";

    private static string Quote(string? s) =>
        string.IsNullOrEmpty(s) ? "—" : $"`{(s.Length <= 44 ? s : s[..44] + "…")}`";

    /// <summary>Which surface the case AUTHORED a personnummer on. Never the value.</summary>
    private static string AuthoredPnr(LayoutCaseObservation c)
    {
        var body = c.Case.Model.SyntheticPersonnummer is not null;
        var account = !string.Equals(
            c.Case.AccountDisplayName, LayoutCaseCatalog.DefaultAccountName, StringComparison.Ordinal);

        return (body, account) switch
        {
            (true, _) => "body (synthetic, not printed)",
            (false, true) => "account name (synthetic, not printed)",
            _ => "none",
        };
    }

    /// <summary>The Domain constraint code behind this row's block, or why there is none.
    ///
    /// <para>THREE outcomes, and the third must not collapse into the second: a code, an em-dash
    /// meaning "no Domain refusal produced one" (every promoted row, every policy block), and an
    /// explicit instrument marker meaning the value could not be READ.</para>
    ///
    /// <para><b>What carries that is the separate observed FIELD, not this method's arm order.</b>
    /// An unreadable reading also leaves the code null, so the two are indistinguishable from the
    /// code alone: a renderer written as "null → em-dash, else the code" prints the em-dash over
    /// an unreadable row, and the artifact then states as a fact about the CV something it merely
    /// failed to observe. Swapping the two non-default arms below changes nothing — an unreadable
    /// row cannot also carry a code — which is exactly why the guard has to be its own observed
    /// value rather than a nullness test here.</para></summary>
    private static string DomainCode(LayoutCaseObservation c) =>
        c.BlockDetailUnreadable ? "**INSTRUMENT: unreadable**"
        // `is not null`, not a Length guard. The claim behind that is scoped to what can be
        // checked: the codes reachable on this path are the thirty-six literals
        // `Resume.CreateFromParsed` declares, none of them empty — NOT a repo-wide claim about
        // every DomainError anywhere. Testing for emptiness would map a value that cannot occur
        // onto the same em-dash as a value that legitimately does, inventing a third silent
        // reading of the cell — the collapse BlockDetailUnreadable exists to prevent. No test
        // pins either polarity, because no fixture can produce an empty code without inventing
        // one; the narrowing is the guard here, not an assertion.
        : c.DomainErrorCode is { } code ? $"`{code}`"
        : "—";

    private static string Y(bool v) => v ? "yes" : "no";

    private static string YN(bool? v) => v is null ? "—" : Y(v.Value);

    private static string Short(GateState s) => s switch
    {
        GateState.Passed => "passed",
        GateState.Blocked => "**BLOCKED**",
        GateState.NotEvaluated => "not evaluated",
        GateState.NoVerdict => "no verdict",

        // Unresolved AND any future member fall here deliberately. The fail-safe direction is "the
        // ladder does not know": an unmapped state must never inherit a sentence that asserts
        // something about the HANDLER, which is how `no verdict` came to be printed over an honest
        // block for a whole PR.
        _ => "unresolved",
    };
}
